# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48a2ae6a5bb7afb5c7d8de55fa9d022199f74bbf7b93b5410e626b980a7f1966fc5fe952307759ff971226e37de29b76e870d2c362c10549ca2f4964fe59f814

test:
  secret_key_base: fda80753067e7e3db9e098c27158a1cd1ef685a61b586a06f8d01c44b53c8a73633ef24e2e6ebf9ac7d09993558bf0f4fba3d17af3c76031177cf787884527e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
